export const theme = {
    /*  bg: "white",
     lightgrey: "#eee",
     ddgrey: "#495057",
     dddgrey: "#222529",
     red: 'red',
     star: '#FFC09F',
     stardone: '#FFE4D6', */
    black: {
        bg: "#ffffff",
        llgrey: '#f1f3f5',
        dgrey: '#868e96',
        ddgrey: "#495057",
        dddgrey: "#222529",
    },
    blue: {
        bg: "#fdfdfd",
        llgrey: "#b9ddfa",
        dgrey: '#43a3dc',
        ddgrey: "#0373b6",
        dddgrey: "#28517b",
    },
    peach: {
        bg: "#fbebde",
        llgrey: "#f9d1b6",
        dgrey: '#cc6952',
        ddgrey: "#b74f4e",
        dddgrey: "#af2627",
    },
    lavender: {
        bg: "#fcf9f8",
        llgrey: "#dae7f8",
        dgrey: '#a3a2df',
        ddgrey: "#6e73d7",
        dddgrey: "#6245a9",
    },
    cherry: {
        bg: "#fdf1e0",
        llgrey: "#ffcabb",
        dgrey: '#f39fa1',
        ddgrey: "#ea5268",
        dddgrey: "#a01261",
    },
    pink: {
        bg: "#fefdff",
        llgrey: "#f6dcec",
        dgrey: '#e996b6',
        ddgrey: "#d8527f",
        dddgrey: "#cd2456",
    },
    beige: {
        bg: "#fdfeff",
        llgrey: "#d2c7a9",
        dgrey: '#a89064',
        ddgrey: "#856537",
        dddgrey: "#5a4f3c",
    },
    darkblue: {
        bg: "#fcffff",
        llgrey: "#E8EBEF",
        dgrey: '#96a3af',
        ddgrey: "#55728b",
        dddgrey: "#1e3865",
    },
    darkgreen: {
        bg: "#fdfeff",
        llgrey: "#dddadc",
        dgrey: '#a0aca3',
        ddgrey: "#5c6d5e",
        dddgrey: "#404C42",
    },
    natural: {
        bg: "#fdfeff",
        llgrey: "#f0dba7",
        dgrey: '#dba64c',
        ddgrey: "#757b50",
        dddgrey: "#525c49",
    }
}